steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - py-cloud
  - --gen2
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --entry-point=hello_get
  - --run-service-account=my-test-project-351918@appspot.gserviceaccount.com
  - --region=us-central1
  - --memory=1G
  - --timeout=3600
  - --cpu=1
logsBucket: 'gs://build_storage'
options:
  logging: GCS_ONLY