steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_http
  - --gen2
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --run-service-account=my-test-project-351918@appspot.gserviceaccount.com
  - --region=us-central1
logsBucket: 'gs://build_storage'
options:
  logging: GCS_ONLY
